
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

rootProject.name = 'proyecto-base'

include 'app-service'
include 'model'
include 'usecase'
include 'mongo-repository'
include 'reactive-web'

project(':app-service').projectDir = file('applications/app-service')
project(':model').projectDir = file('domain/model')
project(':usecase').projectDir = file('domain/usecase')
project(':mongo-repository').projectDir = file('infrastructure/driven-adapters/mongo-repository')
project(':reactive-web').projectDir = file('infrastructure/entry-points/reactive-web')
