dependencies {
    implementation project(':model')
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'
    implementation group: 'org.reactivecommons.utils', name: 'object-mapper', version: '0.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'

}