spring.application.name=store-db
server.port=8081

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/store-db